---
title: "Module 5 - Mosaic Displays 2"
author: "Rushabh Barbhaya"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import, warning=FALSE, message=FALSE, echo=FALSE}
library(kableExtra)
library(dplyr)
library(grid)
library(vcd)
library(data.table)
library(MASS)

data <- read.csv('data.csv', sep = ',', stringsAsFactors = T)
levels(data$Improved)[levels(data$Improved)=="N"] ="No"
levels(data$Improved)[levels(data$Improved)=="Y"] ="Yes"
levels(data$Gender)[levels(data$Gender)=="M"] ="Male"
levels(data$Gender)[levels(data$Gender)=="F"] ="Female"
data = table(data)
placebo = margin.table(data, 4:5)
placebo_gender = margin.table(data, c(4,5,2))
placebo_race = margin.table(data, c(4,5,3))

gen_stats = loglm(~ Treatment * Improved + Gender, data = placebo_gender)
race_stats = loglm(~ Treatment * Improved + Race, data = placebo_race)
```


# Analysis
1. There [is] no evidence to suggest that Gender impacts this joint association ($\chi^2 = `r gen_stats$pearson`\ p\ >0.05 \ (0.08539559)$).
2. [Likewise], there [is no] evidence to suggest that Race impacts this joint association ($\chi^2 = `r race_stats$pearson`\ p\ >0.05 \ (0.8659535)$).

# Tables and Figures
```{r diag, echo=FALSE}
mosaic(placebo, expected = ~ Treatment + Improved,
       shade = T, labeling = labeling_values)
mosaic(placebo_gender, expected = ~ Treatment * Improved + Gender,
       labeling = labeling_values, rot_labels = c(0,0,0,90),
       shade = T)
mosaic(placebo_race, expected = ~ Treatment * Improved + Race,
       labeling = labeling_values, rot_labels = c(0,0,0,90),
       shade = T)
```
